apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: application-passwords
  namespace: xchemlab
spec:
  encryptedData:
    passwords: AgCALIOXYoCZlI3qJHUwxAGlCF5T2RqhzRGJ6WILt/feRkKdwkicFpCpdjbkLoZMutgIFbmSZtCxUopvocUTVVvy08thDwy/Vuc/tpVhGuKqGbhf7YB8Kohy4lXKfNQjuyIlIlrKlp2EvweNDC2czBwkKP2IKNcBjwO66CyE8JNUuva15UdVA+PrEeaQ+9t5bQclGafYoPnAfh/JBDVdUoHu5UESDycyXTl6IA6jXhgckXuN4mRfrkdXxJgpob2DQCmGDj8d6QBhsNjhYaJJVkK3wr3hbdHvsZGzRMsrZEeNgYGKjBkAyRxgBQqWJITA25yQIi+oWiCW0plkQZw0zEzIDH5ZP85gWCTksY/kBbSW0oaSfdIOj/6X/WpEhfjowEX99pyr6zeYCC+JvXMx/PfkkwbVdevWC4IydXXUi+kctPgBk0Cww12+vGk2u22u0tHX6QpyWcmvETlHHC13oJta/K6CdHbRtyBpnyVORwMYuIuc+gh3BSAzIlYekzWp+/998/0uywg1PUBR7TbpbZyyEFZb2ShYaqYajV7YeYP72wAG3NjvIRQAa4cyk5iXVms/hHKED5IqveeJf88ksrvdmeTqoSdTlxCaixDgyhUzaLIv6ZPv9olFS6k5IyWZ20bwjm4cPGlq5MHs6buDIRZYWs2pXIGuhA8PWByaptWtCJQWB2jOfCzUdSv0+gYjIAJOe525moLuBDUbT9YpDmH3
    usernames: AgCQwvol+C036DNxeVfjDDtfr1LQcl+CI9R/ZjOJ/5Ctx5yawz3Xnv8AfIpvDR79+wFLkXwwng2vY3rSw462Cjj/X5FxHqzqkp9S2bNV8SlG5cb8X9wYoFrqvOq5IPDJv+HgwIdAv15kgBnT1eBr23FGovBa4TasfKQIF63DD2xx4xKsUllkXr9MrdmOz/dgtyJxwPLDE2DtTVD71IXvFucLavr6oFXCKIJ12NR556hKE1xdZZgKaNnJeLil33KA5P1MiQ8tXrco1aPbUqZ5JB2FPF3wNxW6Wmw/AeptT3QJj6QObYdSEM4/HGB+zxHEvRAXrk+9CwFZ+w57fODnDffghxrPkReFmWKLOiXBPB8YqVz5MPK8fpPMPVrFcG4YPy03LHJtboaTs1Slk0O+HxzQeeA0BOrl6Uy9TmNxZIOt202jbrkGhtLhJJnAZFfr4vrhdmALF7+aAAkDeVTF0nycCnnmo2ZHGrvlIK02PaphhGw6iuLR+8/efZNl8IErVIehwCH9+u0sIik7+FwPYNlpYeRcNmsQoJmJuy1avyowcDnHInf57s+ZlAxKbbjUX/EIO5ebuoT45kLV5MpeDIQbYS77fg3SRdaMO3OnMEv2WwYc6Tg+N8q89UAk6wqqu0VEVfng39hg/tZQmKb9O4oCosFSdobFC9I3Kf49Qh8/N4FnfaPYRWsjf6zVCVwz+hGbkmqhadv7gA==
  template:
    metadata:
      creationTimestamp: null
      name: application-passwords
      namespace: xchemlab
